Page({
    data:{
        legends:[
            {
                name:'阿卡丽',
                title:'刺客'
            },
            {
                name:'盖伦',
                title:'战士'
            },
            {
                name:'狐狸',
                title:'法师'
            },        
    ]
    }
})
